import { describe, it, expect, vi } from 'vitest';
import { run, runCLI } from '../helper.js';
import * as issueModule from '../../utils/issue.js';

describe('bug', () => {
  it('should preview a bug report as text', async () => {
    const out = await run('bug', '--title', 'Test bug');
    expect(out).toContain('Repository: ant-design/ant-design');
    expect(out).toContain('Title: Test bug');
    expect(out).toContain('--- Issue Body ---');
    expect(out).toContain('### Reproduction link');
    expect(out).toContain('To submit, re-run with --submit flag.');
  });

  it('should preview a bug report as JSON', async () => {
    const out = await run('bug', '--title', 'Test bug', '--format', 'json');
    const data = JSON.parse(out);
    expect(data.repo).toBe('ant-design/ant-design');
    expect(data.title).toBe('Test bug');
    expect(data.body).toContain('<!-- generated by ant-design-issue-helper');
    expect(data.url).toContain('https://github.com/ant-design/ant-design/issues/new');
  });

  it('should include provided fields in bug report', async () => {
    const out = await run('bug', '--title', 'Test', '--steps', 'Click button', '--expected', 'Works', '--actual', 'Crashes', '--format', 'json');
    const data = JSON.parse(out);
    expect(data.body).toContain('Click button');
    expect(data.body).toContain('Works');
    expect(data.body).toContain('Crashes');
  });

  it('should preview bug report as markdown (raw body)', async () => {
    const out = await run('bug', '--title', 'Test', '--format', 'markdown');
    expect(out).toContain('<!-- generated by ant-design-issue-helper');
    expect(out).not.toContain('Repository:');
  });

  it('should error when --title is missing for bug', async () => {
    const result = await runCLI('bug', '--format', 'json');
    expect(result.exitCode).not.toBe(0);
    const err = JSON.parse(result.stderr);
    expect(err.code).toBe('TITLE_REQUIRED');
    expect(err.message).toContain('--title');
  });
});

describe('bug-cli', () => {
  it('should preview a bug-cli report as text', async () => {
    const out = await run('bug-cli', '--title', 'CLI test bug');
    expect(out).toContain('Repository: ant-design/ant-design-cli');
    expect(out).toContain('Title: CLI test bug');
    expect(out).toContain('### Description');
  });

  it('should preview a bug-cli report as JSON', async () => {
    const out = await run('bug-cli', '--title', 'CLI test bug', '--format', 'json');
    const data = JSON.parse(out);
    expect(data.repo).toBe('ant-design/ant-design-cli');
    expect(data.title).toBe('CLI test bug');
    expect(data.body).toContain('### Description');
    expect(data.body).toContain('@ant-design/cli');
    expect(data.url).toContain('https://github.com/ant-design/ant-design-cli/issues/new');
  });

  it('should include description in bug-cli report', async () => {
    const out = await run('bug-cli', '--title', 'Test', '--description', 'Info crashes', '--format', 'json');
    const data = JSON.parse(out);
    expect(data.body).toContain('Info crashes');
  });

  it('should error when --title is missing for bug-cli', async () => {
    const result = await runCLI('bug-cli', '--format', 'json');
    expect(result.exitCode).not.toBe(0);
    const err = JSON.parse(result.stderr);
    expect(err.code).toBe('TITLE_REQUIRED');
    expect(err.message).toContain('--title');
  });

  it('should preview bug-cli report as markdown (raw body)', async () => {
    const out = await run('bug-cli', '--title', 'CLI Test', '--format', 'markdown');
    expect(out).toContain('### Description');
    expect(out).not.toContain('Repository:');
  });
});

describe('bug --submit', () => {
  it('errors when gh is missing', async () => {
    const ghSpy = vi.spyOn(issueModule, 'checkGhAvailable').mockReturnValue(false);
    try {
      const result = await runCLI('bug', '--title', 'X', '--submit', '--format', 'json');
      expect(result.exitCode).toBe(1);
      const err = JSON.parse(result.stderr);
      expect(err.code).toBe('GH_NOT_FOUND');
    } finally {
      ghSpy.mockRestore();
    }
  });

  it('prints created issue URL on success (text)', async () => {
    const ghSpy = vi.spyOn(issueModule, 'checkGhAvailable').mockReturnValue(true);
    const submitSpy = vi.spyOn(issueModule, 'submitViaGh').mockReturnValue({
      issueNumber: 123,
      url: 'https://github.com/ant-design/ant-design/issues/123',
    });
    try {
      const out = await run('bug', '--title', 'X', '--submit');
      expect(out).toContain('Issue created:');
      expect(out).toContain('/issues/123');
    } finally {
      ghSpy.mockRestore();
      submitSpy.mockRestore();
    }
  });

  it('returns JSON when --format json on success', async () => {
    const ghSpy = vi.spyOn(issueModule, 'checkGhAvailable').mockReturnValue(true);
    const submitSpy = vi.spyOn(issueModule, 'submitViaGh').mockReturnValue({
      issueNumber: 42,
      url: 'https://github.com/ant-design/ant-design/issues/42',
    });
    try {
      const out = await run('bug', '--title', 'X', '--submit', '--format', 'json');
      const data = JSON.parse(out);
      expect(data.issueNumber).toBe(42);
      expect(data.repo).toBe('ant-design/ant-design');
    } finally {
      ghSpy.mockRestore();
      submitSpy.mockRestore();
    }
  });

  it('reports failure with exit code 2 when gh throws', async () => {
    const ghSpy = vi.spyOn(issueModule, 'checkGhAvailable').mockReturnValue(true);
    const submitSpy = vi.spyOn(issueModule, 'submitViaGh').mockImplementation(() => {
      throw new Error('auth failed');
    });
    try {
      const result = await runCLI('bug', '--title', 'X', '--submit', '--format', 'json');
      expect(result.exitCode).toBe(2);
      const err = JSON.parse(result.stderr);
      expect(err.code).toBe('GH_SUBMIT_FAILED');
      expect(err.message).toContain('auth failed');
    } finally {
      ghSpy.mockRestore();
      submitSpy.mockRestore();
    }
  });
});

describe('bug-cli --submit', () => {
  it('errors when gh is missing', async () => {
    const ghSpy = vi.spyOn(issueModule, 'checkGhAvailable').mockReturnValue(false);
    try {
      const result = await runCLI('bug-cli', '--title', 'X', '--submit', '--format', 'json');
      expect(result.exitCode).toBe(1);
      const err = JSON.parse(result.stderr);
      expect(err.code).toBe('GH_NOT_FOUND');
    } finally {
      ghSpy.mockRestore();
    }
  });

  it('prints created issue URL on success (text)', async () => {
    const ghSpy = vi.spyOn(issueModule, 'checkGhAvailable').mockReturnValue(true);
    const submitSpy = vi.spyOn(issueModule, 'submitViaGh').mockReturnValue({
      issueNumber: 7,
      url: 'https://github.com/ant-design/ant-design-cli/issues/7',
    });
    try {
      const out = await run('bug-cli', '--title', 'X', '--submit');
      expect(out).toContain('Issue created:');
      expect(out).toContain('/issues/7');
    } finally {
      ghSpy.mockRestore();
      submitSpy.mockRestore();
    }
  });

  it('returns JSON when --format json on success', async () => {
    const ghSpy = vi.spyOn(issueModule, 'checkGhAvailable').mockReturnValue(true);
    const submitSpy = vi.spyOn(issueModule, 'submitViaGh').mockReturnValue({
      issueNumber: 9,
      url: 'https://github.com/ant-design/ant-design-cli/issues/9',
    });
    try {
      const out = await run('bug-cli', '--title', 'X', '--submit', '--format', 'json');
      const data = JSON.parse(out);
      expect(data.issueNumber).toBe(9);
      expect(data.repo).toBe('ant-design/ant-design-cli');
    } finally {
      ghSpy.mockRestore();
      submitSpy.mockRestore();
    }
  });

  it('reports failure with exit code 2 when gh throws', async () => {
    const ghSpy = vi.spyOn(issueModule, 'checkGhAvailable').mockReturnValue(true);
    const submitSpy = vi.spyOn(issueModule, 'submitViaGh').mockImplementation(() => {
      throw new Error('auth failed');
    });
    try {
      const result = await runCLI('bug-cli', '--title', 'X', '--submit', '--format', 'json');
      expect(result.exitCode).toBe(2);
      const err = JSON.parse(result.stderr);
      expect(err.code).toBe('GH_SUBMIT_FAILED');
      expect(err.message).toContain('auth failed');
    } finally {
      ghSpy.mockRestore();
      submitSpy.mockRestore();
    }
  });
});