import { describe, it, expect, vi, afterEach } from 'vitest';
import { ErrorCodes } from '../output/error.js';

describe('bug command error codes', () => {
  it('should have TITLE_REQUIRED error code', () => {
    expect(ErrorCodes.TITLE_REQUIRED).toBe('TITLE_REQUIRED');
  });

  it('should have GH_NOT_FOUND error code', () => {
    expect(ErrorCodes.GH_NOT_FOUND).toBe('GH_NOT_FOUND');
  });

  it('should have GH_SUBMIT_FAILED error code', () => {
    expect(ErrorCodes.GH_SUBMIT_FAILED).toBe('GH_SUBMIT_FAILED');
  });
});

import { collectAntdEnv, collectCliEnv } from '../utils/issue.js';

describe('collectAntdEnv', () => {
  it('should return unknown when node_modules does not exist', () => {
    const env = collectAntdEnv('/tmp/nonexistent-dir-xyz');
    expect(env.antd).toBe('unknown');
    expect(env.react).toBe('unknown');
    expect(env.system).toBeTruthy();
  });

  it('should accept a version override', () => {
    const env = collectAntdEnv('/tmp/nonexistent-dir-xyz', '5.20.0');
    expect(env.antd).toBe('5.20.0');
  });
});

describe('collectCliEnv', () => {
  it('should return CLI version and Node version', () => {
    const env = collectCliEnv();
    expect(env.cli).toBeTruthy();
    expect(env.node).toBe(process.version);
    expect(env.system).toBeTruthy();
  });
});

import { buildAntdIssueBody, buildCliIssueBody, buildIssueUrl } from '../utils/issue.js';

describe('buildAntdIssueBody', () => {
  it('should produce antd-issue-helper format', () => {
    const body = buildAntdIssueBody({
      reproduction: 'https://codesandbox.io/s/test',
      steps: '1. Click button',
      expected: 'Works',
      actual: 'Crashes',
      env: { antd: '5.29.3', react: '18.3.1', system: 'darwin 24.0', browser: '-' },
    });
    expect(body).toContain('<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->');
    expect(body).toContain('### Reproduction link');
    expect(body).toContain('https://codesandbox.io/s/test');
    expect(body).toContain('| antd | 5.29.3 |');
    expect(body).toContain('| React | 18.3.1 |');
    expect(body).toContain('Generated by [@ant-design/cli](https://github.com/ant-design/ant-design-cli)');
  });

  it('should use placeholder for empty fields', () => {
    const body = buildAntdIssueBody({
      env: { antd: '5.29.3', react: '18.3.1', system: 'darwin 24.0', browser: '-' },
    });
    expect(body).toContain('_No response_');
  });
});

describe('buildCliIssueBody', () => {
  it('should produce CLI issue format', () => {
    const body = buildCliIssueBody({
      description: 'Info crashes',
      steps: '1. Run antd info',
      expected: 'Shows props',
      actual: 'Crashes',
      env: { cli: '6.3.3', node: 'v20.11.0', system: 'darwin 24.0' },
    });
    expect(body).toContain('### Description');
    expect(body).toContain('Info crashes');
    expect(body).toContain('| @ant-design/cli | 6.3.3 |');
    expect(body).toContain('Generated by [@ant-design/cli](https://github.com/ant-design/ant-design-cli)');
  });
});

describe('buildIssueUrl', () => {
  it('should produce a valid GitHub new issue URL', () => {
    const url = buildIssueUrl('ant-design/ant-design', 'Test title', 'Test body');
    expect(url).toMatch(/^https:\/\/github\.com\/ant-design\/ant-design\/issues\/new\?/);
    expect(url).toContain('title=Test+title');
  });

  it('should truncate body when URL exceeds 8000 chars', () => {
    const longBody = 'x'.repeat(10000);
    const url = buildIssueUrl('ant-design/ant-design', 'Title', longBody);
    expect(url.length).toBeLessThanOrEqual(8000);
    expect(url).toContain('Content+truncated');
  });
});

import { checkGhAvailable } from '../utils/issue.js';

describe('checkGhAvailable', () => {
  it('should return a boolean', () => {
    const result = checkGhAvailable();
    expect(typeof result).toBe('boolean');
  });
});

import { registerBugCommand, registerBugCliCommand } from '../commands/bug.js';
import { Command } from 'commander';

function createProgram(opts: { format?: string; version?: string; lang?: string; detail?: boolean } = {}) {
  const program = new Command();
  program.exitOverride();
  program.configureOutput({ writeOut: () => {}, writeErr: () => {} });
  program.option('--format <format>', 'Output format', opts.format ?? 'text');
  program.option('--version <version>', 'Target antd version', opts.version);
  program.option('--lang <lang>', 'Output language', opts.lang ?? 'en');
  program.option('--detail', 'Full information output', opts.detail ?? false);
  return program;
}

describe('registerBugCommand', () => {
  it('should register the bug command', () => {
    const program = new Command();
    registerBugCommand(program);
    const cmd = program.commands.find((c) => c.name() === 'bug');
    expect(cmd).toBeDefined();
    expect(cmd!.description()).toContain('antd');
  });
});

describe('registerBugCliCommand', () => {
  it('should register the bug-cli command', () => {
    const program = new Command();
    registerBugCliCommand(program);
    const cmd = program.commands.find((c) => c.name() === 'bug-cli');
    expect(cmd).toBeDefined();
    expect(cmd!.description()).toContain('cli');
  });
});

describe('bug command action', () => {
  afterEach(() => {
    vi.restoreAllMocks();
    process.exitCode = undefined;
  });

  it('should error when title is missing', async () => {
    const program = createProgram();
    registerBugCommand(program);
    const errSpy = vi.spyOn(console, 'error').mockImplementation(() => {});
    const exitSpy = vi.spyOn(process, 'exit').mockImplementation(() => undefined as never);
    await program.parseAsync(['node', 'test', 'bug'], );
    expect(errSpy).toHaveBeenCalled();
    expect(exitSpy).toHaveBeenCalledWith(1);
  });

  it('should output preview in text format', async () => {
    const program = createProgram();
    registerBugCommand(program);
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    await program.parseAsync(['node', 'test', 'bug', '--title', 'Test Bug'], );
    const allOutput = logSpy.mock.calls.map((c) => c[0]).join('\n');
    expect(allOutput).toContain('Repository: ant-design/ant-design');
    expect(allOutput).toContain('Title: Test Bug');
    expect(allOutput).toContain('--submit');
  });

  it('should output preview in JSON format', async () => {
    const program = createProgram({ format: 'json' });
    registerBugCommand(program);
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    await program.parseAsync(['node', 'test', 'bug', '--title', 'Test Bug'], );
    const parsed = JSON.parse(logSpy.mock.calls[0][0]);
    expect(parsed.repo).toBe('ant-design/ant-design');
    expect(parsed.title).toBe('Test Bug');
    expect(parsed.url).toBeDefined();
  });

  it('should output preview in markdown format', async () => {
    const program = createProgram({ format: 'markdown' });
    registerBugCommand(program);
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    await program.parseAsync(['node', 'test', 'bug', '--title', 'Test Bug'], );
    const output = logSpy.mock.calls[0][0];
    expect(output).toContain('generated by ant-design-issue-helper');
  });
});

describe('bug-cli command action', () => {
  afterEach(() => {
    vi.restoreAllMocks();
    process.exitCode = undefined;
  });

  it('should error when title is missing', async () => {
    const program = createProgram();
    registerBugCliCommand(program);
    const errSpy = vi.spyOn(console, 'error').mockImplementation(() => {});
    const exitSpy = vi.spyOn(process, 'exit').mockImplementation(() => undefined as never);
    await program.parseAsync(['node', 'test', 'bug-cli'], );
    expect(errSpy).toHaveBeenCalled();
    expect(exitSpy).toHaveBeenCalledWith(1);
  });

  it('should output preview in text format', async () => {
    const program = createProgram();
    registerBugCliCommand(program);
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    await program.parseAsync(['node', 'test', 'bug-cli', '--title', 'Test Bug'], );
    const allOutput = logSpy.mock.calls.map((c) => c[0]).join('\n');
    expect(allOutput).toContain('Repository: ant-design/ant-design-cli');
    expect(allOutput).toContain('Title: Test Bug');
  });

  it('should output preview in JSON format', async () => {
    const program = createProgram({ format: 'json' });
    registerBugCliCommand(program);
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    await program.parseAsync(['node', 'test', 'bug-cli', '--title', 'Test Bug'], );
    const parsed = JSON.parse(logSpy.mock.calls[0][0]);
    expect(parsed.repo).toBe('ant-design/ant-design-cli');
    expect(parsed.title).toBe('Test Bug');
  });

  it('should output preview in markdown format', async () => {
    const program = createProgram({ format: 'markdown' });
    registerBugCliCommand(program);
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    await program.parseAsync(['node', 'test', 'bug-cli', '--title', 'Test Bug'], );
    const output = logSpy.mock.calls[0][0];
    expect(output).toContain('### Description');
  });
});

describe('submitViaGh', () => {
  it('should be importable', async () => {
    const { submitViaGh } = await import('../utils/issue.js');
    expect(typeof submitViaGh).toBe('function');
  });
});

// --- Submit flow tests ---
// We use vi.mock to intercept checkGhAvailable and submitViaGh at the module level.
vi.mock('../utils/issue.js', async (importOriginal) => {
  const actual = await importOriginal<typeof import('../utils/issue.js')>();
  return {
    ...actual,
    checkGhAvailable: vi.fn(() => false),
    submitViaGh: vi.fn(() => ({ issueNumber: 0, url: '' })),
  };
});

import { checkGhAvailable as checkGhAvailableMock, submitViaGh as submitViaGhMock } from '../utils/issue.js';

const mockedCheckGh = vi.mocked(checkGhAvailableMock);
const mockedSubmitGh = vi.mocked(submitViaGhMock);

describe('bug command --submit flow', () => {
  afterEach(() => {
    vi.restoreAllMocks();
    mockedCheckGh.mockReset();
    mockedSubmitGh.mockReset();
    process.exitCode = undefined;
  });

  it('should error when gh is not available', async () => {
    mockedCheckGh.mockReturnValue(false);
    const program = createProgram();
    registerBugCommand(program);
    const errSpy = vi.spyOn(console, 'error').mockImplementation(() => {});
    const exitSpy = vi.spyOn(process, 'exit').mockImplementation(() => undefined as never);
    await program.parseAsync(['node', 'test', 'bug', '--title', 'Test', '--submit']);
    expect(exitSpy).toHaveBeenCalledWith(1);
    expect(errSpy).toHaveBeenCalled();
    const errOutput = errSpy.mock.calls.map((c) => c.join(' ')).join('\n');
    expect(errOutput).toContain('gh CLI is not installed');
  });

  it('should submit successfully in text format', async () => {
    mockedCheckGh.mockReturnValue(true);
    mockedSubmitGh.mockReturnValue({ issueNumber: 42, url: 'https://github.com/ant-design/ant-design/issues/42' });
    const program = createProgram();
    registerBugCommand(program);
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    await program.parseAsync(['node', 'test', 'bug', '--title', 'Test', '--submit']);
    expect(logSpy).toHaveBeenCalledWith('Issue created: https://github.com/ant-design/ant-design/issues/42');
  });

  it('should submit successfully in json format', async () => {
    mockedCheckGh.mockReturnValue(true);
    mockedSubmitGh.mockReturnValue({ issueNumber: 42, url: 'https://github.com/ant-design/ant-design/issues/42' });
    const program = createProgram({ format: 'json' });
    registerBugCommand(program);
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    await program.parseAsync(['node', 'test', 'bug', '--title', 'Test', '--submit']);
    const parsed = JSON.parse(logSpy.mock.calls[0][0]);
    expect(parsed.repo).toBe('ant-design/ant-design');
    expect(parsed.issueNumber).toBe(42);
    expect(parsed.url).toContain('issues/42');
  });

  it('should error when gh submit fails', async () => {
    mockedCheckGh.mockReturnValue(true);
    mockedSubmitGh.mockImplementation(() => { throw new Error('auth failed'); });
    const program = createProgram();
    registerBugCommand(program);
    const errSpy = vi.spyOn(console, 'error').mockImplementation(() => {});
    const exitSpy = vi.spyOn(process, 'exit').mockImplementation(() => undefined as never);
    await program.parseAsync(['node', 'test', 'bug', '--title', 'Test', '--submit']);
    expect(exitSpy).toHaveBeenCalledWith(2);
    const errOutput = errSpy.mock.calls.map((c) => c.join(' ')).join('\n');
    expect(errOutput).toContain('Failed to create issue: auth failed');
  });

  it('should handle non-Error throw in submit', async () => {
    mockedCheckGh.mockReturnValue(true);
    mockedSubmitGh.mockImplementation(() => { throw 'string error'; });
    const program = createProgram();
    registerBugCommand(program);
    vi.spyOn(console, 'error').mockImplementation(() => {});
    const exitSpy = vi.spyOn(process, 'exit').mockImplementation(() => undefined as never);
    await program.parseAsync(['node', 'test', 'bug', '--title', 'Test', '--submit']);
    expect(exitSpy).toHaveBeenCalledWith(2);
  });
});

describe('bug-cli command --submit flow', () => {
  afterEach(() => {
    vi.restoreAllMocks();
    mockedCheckGh.mockReset();
    mockedSubmitGh.mockReset();
    process.exitCode = undefined;
  });

  it('should error when gh is not available', async () => {
    mockedCheckGh.mockReturnValue(false);
    const program = createProgram();
    registerBugCliCommand(program);
    const errSpy = vi.spyOn(console, 'error').mockImplementation(() => {});
    const exitSpy = vi.spyOn(process, 'exit').mockImplementation(() => undefined as never);
    await program.parseAsync(['node', 'test', 'bug-cli', '--title', 'Test', '--submit']);
    expect(exitSpy).toHaveBeenCalledWith(1);
    const errOutput = errSpy.mock.calls.map((c) => c.join(' ')).join('\n');
    expect(errOutput).toContain('gh CLI is not installed');
  });

  it('should submit successfully in text format', async () => {
    mockedCheckGh.mockReturnValue(true);
    mockedSubmitGh.mockReturnValue({ issueNumber: 99, url: 'https://github.com/ant-design/ant-design-cli/issues/99' });
    const program = createProgram();
    registerBugCliCommand(program);
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    await program.parseAsync(['node', 'test', 'bug-cli', '--title', 'Test', '--submit']);
    expect(logSpy).toHaveBeenCalledWith('Issue created: https://github.com/ant-design/ant-design-cli/issues/99');
  });

  it('should submit successfully in json format', async () => {
    mockedCheckGh.mockReturnValue(true);
    mockedSubmitGh.mockReturnValue({ issueNumber: 99, url: 'https://github.com/ant-design/ant-design-cli/issues/99' });
    const program = createProgram({ format: 'json' });
    registerBugCliCommand(program);
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    await program.parseAsync(['node', 'test', 'bug-cli', '--title', 'Test', '--submit']);
    const parsed = JSON.parse(logSpy.mock.calls[0][0]);
    expect(parsed.repo).toBe('ant-design/ant-design-cli');
    expect(parsed.issueNumber).toBe(99);
  });

  it('should error when gh submit fails', async () => {
    mockedCheckGh.mockReturnValue(true);
    mockedSubmitGh.mockImplementation(() => { throw new Error('auth failed'); });
    const program = createProgram();
    registerBugCliCommand(program);
    const errSpy = vi.spyOn(console, 'error').mockImplementation(() => {});
    const exitSpy = vi.spyOn(process, 'exit').mockImplementation(() => undefined as never);
    await program.parseAsync(['node', 'test', 'bug-cli', '--title', 'Test', '--submit']);
    expect(exitSpy).toHaveBeenCalledWith(2);
    const errOutput = errSpy.mock.calls.map((c) => c.join(' ')).join('\n');
    expect(errOutput).toContain('Failed to create issue: auth failed');
  });
});

describe('issue body with extra field', () => {
  it('should include extra content in antd issue body', () => {
    const body = buildAntdIssueBody({
      reproduction: 'https://example.com',
      extra: 'Additional info here',
      env: { antd: '5.0.0', react: '18.0.0', system: 'linux', browser: 'chrome' },
    });
    expect(body).toContain('Additional info here');
  });

  it('should include extra content in CLI issue body', () => {
    const body = buildCliIssueBody({
      description: 'test',
      extra: 'Extra CLI info',
      env: { cli: '6.0.0', node: 'v18.0.0', system: 'linux' },
    });
    expect(body).toContain('Extra CLI info');
  });
});
