import { describe, it, expect } from 'vitest';
import { ErrorCodes } from '../output/error.js';

describe('bug command error codes', () => {
  it('should have TITLE_REQUIRED error code', () => {
    expect(ErrorCodes.TITLE_REQUIRED).toBe('TITLE_REQUIRED');
  });

  it('should have GH_NOT_FOUND error code', () => {
    expect(ErrorCodes.GH_NOT_FOUND).toBe('GH_NOT_FOUND');
  });

  it('should have GH_SUBMIT_FAILED error code', () => {
    expect(ErrorCodes.GH_SUBMIT_FAILED).toBe('GH_SUBMIT_FAILED');
  });
});

import { collectAntdEnv, collectCliEnv } from '../utils/issue.js';

describe('collectAntdEnv', () => {
  it('should return unknown when node_modules does not exist', () => {
    const env = collectAntdEnv('/tmp/nonexistent-dir-xyz');
    expect(env.antd).toBe('unknown');
    expect(env.react).toBe('unknown');
    expect(env.system).toBeTruthy();
  });

  it('should accept a version override', () => {
    const env = collectAntdEnv('/tmp/nonexistent-dir-xyz', '5.20.0');
    expect(env.antd).toBe('5.20.0');
  });
});

describe('collectCliEnv', () => {
  it('should return CLI version and Node version', () => {
    const env = collectCliEnv();
    expect(env.cli).toBeTruthy();
    expect(env.node).toBe(process.version);
    expect(env.system).toBeTruthy();
  });
});

import { buildAntdIssueBody, buildCliIssueBody, buildIssueUrl } from '../utils/issue.js';

describe('buildAntdIssueBody', () => {
  it('should produce antd-issue-helper format', () => {
    const body = buildAntdIssueBody({
      reproduction: 'https://codesandbox.io/s/test',
      steps: '1. Click button',
      expected: 'Works',
      actual: 'Crashes',
      env: { antd: '5.29.3', react: '18.3.1', system: 'darwin 24.0', browser: '-' },
    });
    expect(body).toContain('<!-- generated by @ant-design/cli. DO NOT REMOVE -->');
    expect(body).toContain('### Reproduction link');
    expect(body).toContain('https://codesandbox.io/s/test');
    expect(body).toContain('| antd | 5.29.3 |');
    expect(body).toContain('| React | 18.3.1 |');
    expect(body).toContain('Generated by [@ant-design/cli](https://github.com/ant-design/ant-design-cli)');
  });

  it('should use placeholder for empty fields', () => {
    const body = buildAntdIssueBody({
      env: { antd: '5.29.3', react: '18.3.1', system: 'darwin 24.0', browser: '-' },
    });
    expect(body).toContain('_No response_');
  });
});

describe('buildCliIssueBody', () => {
  it('should produce CLI issue format', () => {
    const body = buildCliIssueBody({
      description: 'Info crashes',
      steps: '1. Run antd info',
      expected: 'Shows props',
      actual: 'Crashes',
      env: { cli: '6.3.3', node: 'v20.11.0', system: 'darwin 24.0' },
    });
    expect(body).toContain('### Description');
    expect(body).toContain('Info crashes');
    expect(body).toContain('| @ant-design/cli | 6.3.3 |');
    expect(body).toContain('Generated by [@ant-design/cli](https://github.com/ant-design/ant-design-cli)');
  });
});

describe('buildIssueUrl', () => {
  it('should produce a valid GitHub new issue URL', () => {
    const url = buildIssueUrl('ant-design/ant-design', 'Test title', 'Test body');
    expect(url).toMatch(/^https:\/\/github\.com\/ant-design\/ant-design\/issues\/new\?/);
    expect(url).toContain('title=Test+title');
  });

  it('should truncate body when URL exceeds 8000 chars', () => {
    const longBody = 'x'.repeat(10000);
    const url = buildIssueUrl('ant-design/ant-design', 'Title', longBody);
    expect(url.length).toBeLessThanOrEqual(8000);
    expect(url).toContain('Content+truncated');
  });
});

import { checkGhAvailable } from '../utils/issue.js';

describe('checkGhAvailable', () => {
  it('should return a boolean', () => {
    const result = checkGhAvailable();
    expect(typeof result).toBe('boolean');
  });
});

import { registerBugCommand, registerBugCliCommand } from '../commands/bug.js';
import { Command } from 'commander';

describe('registerBugCommand', () => {
  it('should register the bug command', () => {
    const program = new Command();
    registerBugCommand(program);
    const cmd = program.commands.find((c) => c.name() === 'bug');
    expect(cmd).toBeDefined();
    expect(cmd!.description()).toContain('antd');
  });
});

describe('registerBugCliCommand', () => {
  it('should register the bug-cli command', () => {
    const program = new Command();
    registerBugCliCommand(program);
    const cmd = program.commands.find((c) => c.name() === 'bug-cli');
    expect(cmd).toBeDefined();
    expect(cmd!.description()).toContain('cli');
  });
});
