import { describe, it, expect, vi } from 'vitest';
import { execFileSync } from 'node:child_process';
import {
  checkGhAvailable,
  submitViaGh,
  buildIssueUrl,
  buildAntdIssueBody,
  buildCliIssueBody,
  collectAntdEnv,
  collectCliEnv,
} from '../utils/issue.js';

vi.mock('node:child_process', () => ({
  execFileSync: vi.fn(),
}));

const mockedExec = vi.mocked(execFileSync);

describe('issue helpers', () => {
  describe('checkGhAvailable', () => {
    it('returns true when gh --version succeeds', () => {
      mockedExec.mockImplementationOnce(() => Buffer.from('gh version 2.0.0'));
      expect(checkGhAvailable()).toBe(true);
    });

    it('returns false when gh is missing', () => {
      mockedExec.mockImplementationOnce(() => {
        throw new Error('command not found');
      });
      expect(checkGhAvailable()).toBe(false);
    });
  });

  describe('submitViaGh', () => {
    it('returns issueNumber + url parsed from gh output', () => {
      mockedExec.mockImplementationOnce(() => 'https://github.com/ant-design/ant-design/issues/42\n');
      const result = submitViaGh('ant-design/ant-design', 'Title', 'Body');
      expect(result.issueNumber).toBe(42);
      expect(result.url).toContain('/issues/42');
    });

    it('returns issueNumber 0 when URL pattern does not match', () => {
      mockedExec.mockImplementationOnce(() => 'unexpected output');
      const result = submitViaGh('repo/repo', 'Title', 'Body');
      expect(result.issueNumber).toBe(0);
      expect(result.url).toBe('unexpected output');
    });
  });

  describe('buildIssueUrl', () => {
    it('returns a normal URL for short body', () => {
      const url = buildIssueUrl('owner/repo', 'Title', 'short body');
      expect(url).toContain('https://github.com/owner/repo/issues/new');
      expect(url).toContain('title=Title');
      expect(url).toContain('body=short');
    });

    it('truncates long body when URL exceeds 8000 chars', () => {
      const longBody = 'x'.repeat(20000);
      const url = buildIssueUrl('owner/repo', 'Title', longBody);
      expect(url.length).toBeLessThanOrEqual(8000);
      const parsed = new URL(url);
      const decoded = parsed.searchParams.get('body') ?? '';
      expect(decoded).toContain('Content truncated');
    });
  });

  describe('body builders', () => {
    it('buildAntdIssueBody includes all sections and footer', () => {
      const body = buildAntdIssueBody({
        reproduction: 'https://stackblitz.com/example',
        steps: '1. Click',
        expected: 'Works',
        actual: 'Fails',
        extra: 'extra info',
        env: { antd: '5.0.0', react: '18.0.0', system: 'darwin', browser: 'Chrome' },
      });
      expect(body).toContain('### Reproduction link');
      expect(body).toContain('https://stackblitz.com/example');
      expect(body).toContain('1. Click');
      expect(body).toContain('Works');
      expect(body).toContain('Fails');
      expect(body).toContain('extra info');
      expect(body).toContain('Generated by [@ant-design/cli]');
    });

    it('buildAntdIssueBody falls back to placeholders when fields missing', () => {
      const body = buildAntdIssueBody({
        env: { antd: '5.0.0', react: '18.0.0', system: 'darwin', browser: 'Chrome' },
      });
      expect(body).toContain('_No response_');
    });

    it('buildCliIssueBody includes all sections', () => {
      const body = buildCliIssueBody({
        description: 'desc',
        steps: '1. step',
        expected: 'exp',
        actual: 'act',
        extra: 'extra',
        env: { cli: '6.0.0', node: 'v20.0.0', system: 'darwin' },
      });
      expect(body).toContain('### Description');
      expect(body).toContain('desc');
      expect(body).toContain('extra');
    });

    it('buildCliIssueBody falls back to placeholders when fields missing', () => {
      const body = buildCliIssueBody({
        env: { cli: '6.0.0', node: 'v20.0.0', system: 'darwin' },
      });
      expect(body).toContain('_No response_');
    });
  });

  describe('env collectors', () => {
    it('collectAntdEnv returns version override when provided', () => {
      const env = collectAntdEnv(process.cwd(), '6.0.0');
      expect(env.antd).toBe('6.0.0');
    });

    it('collectAntdEnv returns unknown when no antd installed', () => {
      const env = collectAntdEnv('/tmp/nowhere-' + Date.now());
      expect(env.antd).toBe('unknown');
    });

    it('collectCliEnv returns versions and system', () => {
      const env = collectCliEnv();
      expect(env.cli).toBeTruthy();
      expect(env.node).toBe(process.version);
      expect(env.system).toMatch(/.+\s.+/);
    });
  });
});
