import { platform, release } from 'node:os';
import { readJson } from './scan.js';
import { join } from 'node:path';

declare const __CLI_VERSION__: string;

export interface AntdEnv {
  antd: string;
  react: string;
  system: string;
  browser: string;
}

export interface CliEnv {
  cli: string;
  node: string;
  system: string;
}

function getSystem(): string {
  return `${platform()} ${release()}`;
}

export function collectAntdEnv(cwd: string, versionOverride?: string): AntdEnv {
  const antdPkg = readJson(join(cwd, 'node_modules', 'antd', 'package.json'));
  const reactPkg = readJson(join(cwd, 'node_modules', 'react', 'package.json'));

  return {
    antd: versionOverride || antdPkg?.version || 'unknown',
    react: reactPkg?.version || 'unknown',
    system: getSystem(),
    browser: '-',
  };
}

export function collectCliEnv(): CliEnv {
  let cliVersion: string;
  try {
    cliVersion = __CLI_VERSION__;
  } catch {
    cliVersion = 'unknown';
  }
  return {
    cli: cliVersion,
    node: process.version,
    system: getSystem(),
  };
}

const PLACEHOLDER = '_No response_';
const MAX_URL_LENGTH = 8000;

export interface AntdIssueFields {
  reproduction?: string;
  steps?: string;
  expected?: string;
  actual?: string;
  extra?: string;
  env: AntdEnv;
}

export interface CliIssueFields {
  description?: string;
  steps?: string;
  expected?: string;
  actual?: string;
  extra?: string;
  env: CliEnv;
}

export function buildAntdIssueBody(fields: AntdIssueFields): string {
  const reproduction = fields.reproduction || PLACEHOLDER;
  const steps = fields.steps || PLACEHOLDER;
  const expected = fields.expected || PLACEHOLDER;
  const actual = fields.actual || PLACEHOLDER;
  const extra = fields.extra || '';

  let body = `<!-- generated by @ant-design/cli. DO NOT REMOVE -->

### Reproduction link

[${reproduction}](${reproduction})

### Steps to reproduce

${steps}

### What is expected?

${expected}

### What is actually happening?

${actual}

| Environment | Info |
| --- | --- |
| antd | ${fields.env.antd} |
| React | ${fields.env.react} |
| System | ${fields.env.system} |
| Browser | ${fields.env.browser} |`;

  if (extra) {
    body += `\n\n---\n${extra}`;
  }

  return body;
}

export function buildCliIssueBody(fields: CliIssueFields): string {
  const description = fields.description || PLACEHOLDER;
  const steps = fields.steps || PLACEHOLDER;
  const expected = fields.expected || PLACEHOLDER;
  const actual = fields.actual || PLACEHOLDER;
  const extra = fields.extra || '';

  let body = `### Description

${description}

### Steps to Reproduce

${steps}

### Expected Behavior

${expected}

### Actual Behavior

${actual}

### Environment

| Info | Value |
|------|-------|
| @ant-design/cli | ${fields.env.cli} |
| Node | ${fields.env.node} |
| System | ${fields.env.system} |`;

  if (extra) {
    body += `\n\n---\n${extra}`;
  }

  return body;
}

export function buildIssueUrl(repo: string, title: string, body: string): string {
  const baseUrl = `https://github.com/${repo}/issues/new`;
  const params = new URLSearchParams({ title, body });
  let url = `${baseUrl}?${params.toString()}`;

  if (url.length > MAX_URL_LENGTH) {
    const truncationNote = '\n\n(Content truncated. Please add remaining details after opening.)';
    let lo = 0;
    let hi = body.length;
    while (lo < hi) {
      const mid = Math.ceil((lo + hi) / 2);
      const truncated = body.slice(0, mid) + truncationNote;
      const testParams = new URLSearchParams({ title, body: truncated });
      const testUrl = `${baseUrl}?${testParams.toString()}`;
      if (testUrl.length <= MAX_URL_LENGTH) {
        lo = mid;
      } else {
        hi = mid - 1;
      }
    }
    const truncatedBody = body.slice(0, lo) + truncationNote;
    const finalParams = new URLSearchParams({ title, body: truncatedBody });
    url = `${baseUrl}?${finalParams.toString()}`;
  }

  return url;
}
