import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

type Point = { x: number; y: number };
type Bounds = { minX: number; minY: number; maxX: number; maxY: number };
type Color = [number, number, number];
type Gradient = {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  stops: { offset: number; color: Color }[];
};
type PathShape = {
  type: 'path';
  subpaths: Point[][];
  bounds: Bounds;
  gradient: Gradient;
};
type EllipseShape = {
  type: 'ellipse';
  cx: number;
  cy: number;
  rx: number;
  ry: number;
  bounds: Bounds;
  gradient: Gradient;
};
type Shape = PathShape | EllipseShape;
type Pixel = { alpha: number; color: Color };

const __dirname = dirname(fileURLToPath(import.meta.url));
const SOURCE = join(__dirname, 'assets/antd-logo.svg');
const OUTPUT = join(__dirname, '../src/output/logo.ts');
const WIDTH = 18;
const HEIGHT = 18;
const SAMPLES_PER_AXIS = 4;
const VIEWBOX_SIZE = 200;
const FILL_THRESHOLD = 0.28;
const RESET = '\u001b[39m\u001b[49m';

function main(): void {
  const svg = readFileSync(SOURCE, 'utf-8');
  const gradients = parseGradients(svg);
  const shapes = parseShapes(svg, gradients);
  const sampledPixels = sampleLogo(shapes);
  const textLines = renderTextLogo(sampledPixels);
  const ansiLines = renderAnsiLogo(sampledPixels);

  writeFileSync(
    OUTPUT,
    `// This file is generated by scripts/generate-logo.ts. Do not edit manually.\n\n`
      + `export const HELP_LOGO_TEXT = ${formatLines(textLines)};\n\n`
      + `export const HELP_LOGO_ANSI = ${formatLines(ansiLines)};\n`,
  );

  console.log(`Generated ${OUTPUT}`);
}

function parseGradients(source: string): Map<string, Gradient> {
  const result = new Map<string, Gradient>();
  const gradientPattern = /<linearGradient\s+([^>]+)>([\s\S]*?)<\/linearGradient>/g;

  for (const match of source.matchAll(gradientPattern)) {
    const attrs = parseAttributes(match[1]);
    const stops = [...match[2].matchAll(/<stop\s+([^>]+)>/g)].map((stopMatch) => {
      const stopAttrs = parseAttributes(stopMatch[1]);
      return {
        offset: Number.parseFloat(stopAttrs.offset) / 100,
        color: hexToRgb(stopAttrs['stop-color']),
      };
    });

    result.set(attrs.id, {
      x1: Number.parseFloat(attrs.x1) / 100,
      y1: Number.parseFloat(attrs.y1) / 100,
      x2: Number.parseFloat(attrs.x2) / 100,
      y2: Number.parseFloat(attrs.y2) / 100,
      stops,
    });
  }

  return result;
}

function parseShapes(source: string, gradientsById: Map<string, Gradient>): Shape[] {
  const shapes: Shape[] = [];

  for (const match of source.matchAll(/<path\s+([^>]+)>/g)) {
    const attrs = parseAttributes(match[1]);
    const gradient = getGradient(gradientsById, attrs.fill);
    const subpaths = flattenPath(attrs.d);
    shapes.push({
      type: 'path',
      subpaths,
      bounds: getSubpathsBounds(subpaths),
      gradient,
    });
  }

  for (const match of source.matchAll(/<ellipse\s+([^>]+)>/g)) {
    const attrs = parseAttributes(match[1]);
    const cx = Number(attrs.cx);
    const cy = Number(attrs.cy);
    const rx = Number(attrs.rx);
    const ry = Number(attrs.ry);
    shapes.push({
      type: 'ellipse',
      cx,
      cy,
      rx,
      ry,
      bounds: {
        minX: cx - rx,
        minY: cy - ry,
        maxX: cx + rx,
        maxY: cy + ry,
      },
      gradient: getGradient(gradientsById, attrs.fill),
    });
  }

  return shapes;
}

function parseAttributes(input: string): Record<string, string> {
  return Object.fromEntries(
    [...input.matchAll(/([\w:-]+)="([^"]*)"/g)].map((match) => [match[1], match[2]]),
  );
}

function getGradient(gradientsById: Map<string, Gradient>, fill: string): Gradient {
  const id = fill.match(/^url\(#(.+)\)$/)?.[1];
  const gradient = id ? gradientsById.get(id) : undefined;
  if (!gradient) {
    throw new Error(`Missing gradient for ${fill}`);
  }
  return gradient;
}

function flattenPath(pathData: string): Point[][] {
  const tokens = pathData.match(/[A-Za-z]|-?\d*\.?\d+(?:e[-+]?\d+)?/gi);
  if (!tokens) {
    return [];
  }

  const subpaths: Point[][] = [];
  let index = 0;
  let command = '';
  let current: Point = { x: 0, y: 0 };
  let currentPath: Point[] = [];

  while (index < tokens.length) {
    if (/^[A-Za-z]$/.test(tokens[index])) {
      command = tokens[index++];
    }

    switch (command) {
      case 'M': {
        current = readPoint(tokens, index);
        index += 2;
        currentPath = [current];
        subpaths.push(currentPath);
        command = 'L';
        break;
      }

      case 'L': {
        current = readPoint(tokens, index);
        index += 2;
        currentPath.push(current);
        break;
      }

      case 'C': {
        const start = current;
        const control1 = readPoint(tokens, index);
        const control2 = readPoint(tokens, index + 2);
        const end = readPoint(tokens, index + 4);
        index += 6;

        for (let step = 1; step <= 28; step += 1) {
          currentPath.push(getCubicPoint(start, control1, control2, end, step / 28));
        }
        current = end;
        break;
      }

      case 'Z':
      case 'z':
        index += 1;
        break;

      default:
        throw new Error(`Unsupported SVG path command: ${command}`);
    }
  }

  return subpaths;
}

function readPoint(tokens: string[], index: number): Point {
  return {
    x: Number(tokens[index]),
    y: Number(tokens[index + 1]),
  };
}

function getCubicPoint(start: Point, control1: Point, control2: Point, end: Point, t: number): Point {
  const mt = 1 - t;
  return {
    x: (mt ** 3 * start.x) + (3 * mt ** 2 * t * control1.x) + (3 * mt * t ** 2 * control2.x) + (t ** 3 * end.x),
    y: (mt ** 3 * start.y) + (3 * mt ** 2 * t * control1.y) + (3 * mt * t ** 2 * control2.y) + (t ** 3 * end.y),
  };
}

function getSubpathsBounds(subpaths: Point[][]): Bounds {
  const points = subpaths.flat();
  return {
    minX: Math.min(...points.map((point) => point.x)),
    minY: Math.min(...points.map((point) => point.y)),
    maxX: Math.max(...points.map((point) => point.x)),
    maxY: Math.max(...points.map((point) => point.y)),
  };
}

function sampleLogo(shapesToSample: Shape[]): Pixel[][] {
  return Array.from({ length: HEIGHT }, (_, y) => (
    Array.from({ length: WIDTH }, (_, x) => samplePixel(shapesToSample, x, y))
  ));
}

function samplePixel(shapesToSample: Shape[], pixelX: number, pixelY: number): Pixel {
  let hits = 0;
  const color: Color = [0, 0, 0];

  for (let sampleY = 0; sampleY < SAMPLES_PER_AXIS; sampleY += 1) {
    for (let sampleX = 0; sampleX < SAMPLES_PER_AXIS; sampleX += 1) {
      const point = {
        x: ((pixelX + (sampleX + 0.5) / SAMPLES_PER_AXIS) / WIDTH) * VIEWBOX_SIZE,
        y: ((pixelY + (sampleY + 0.5) / SAMPLES_PER_AXIS) / HEIGHT) * VIEWBOX_SIZE,
      };
      const shape = getTopShapeAtPoint(shapesToSample, point);
      if (shape) {
        hits += 1;
        addColor(color, getGradientColor(shape.gradient, shape.bounds, point));
      }
    }
  }

  if (hits === 0) {
    return { alpha: 0, color };
  }

  return {
    alpha: hits / (SAMPLES_PER_AXIS ** 2),
    color: color.map((channel) => Math.round(channel / hits)) as Color,
  };
}

function getTopShapeAtPoint(shapesToSample: Shape[], point: Point): Shape | undefined {
  for (let index = shapesToSample.length - 1; index >= 0; index -= 1) {
    const shape = shapesToSample[index];
    if (containsPoint(shape, point)) {
      return shape;
    }
  }
  return undefined;
}

function containsPoint(shape: Shape, point: Point): boolean {
  if (point.x < shape.bounds.minX || point.x > shape.bounds.maxX || point.y < shape.bounds.minY || point.y > shape.bounds.maxY) {
    return false;
  }

  if (shape.type === 'ellipse') {
    return (((point.x - shape.cx) / shape.rx) ** 2) + (((point.y - shape.cy) / shape.ry) ** 2) <= 1;
  }

  return shape.subpaths.some((subpath) => isInsidePolygon(point, subpath));
}

function isInsidePolygon(point: Point, polygon: Point[]): boolean {
  let inside = false;
  for (let index = 0, previousIndex = polygon.length - 1; index < polygon.length; previousIndex = index, index += 1) {
    const start = polygon[index];
    const end = polygon[previousIndex];
    const intersects = ((start.y > point.y) !== (end.y > point.y))
      && (point.x < ((end.x - start.x) * (point.y - start.y)) / (end.y - start.y) + start.x);
    if (intersects) {
      inside = !inside;
    }
  }
  return inside;
}

function getGradientColor(gradient: Gradient, bounds: Bounds, point: Point): Color {
  const start = {
    x: bounds.minX + gradient.x1 * (bounds.maxX - bounds.minX),
    y: bounds.minY + gradient.y1 * (bounds.maxY - bounds.minY),
  };
  const end = {
    x: bounds.minX + gradient.x2 * (bounds.maxX - bounds.minX),
    y: bounds.minY + gradient.y2 * (bounds.maxY - bounds.minY),
  };
  const vector = { x: end.x - start.x, y: end.y - start.y };
  const length = vector.x ** 2 + vector.y ** 2;
  const offset = length === 0 ? 0 : clamp(((point.x - start.x) * vector.x + (point.y - start.y) * vector.y) / length);

  for (let index = 1; index < gradient.stops.length; index += 1) {
    const previous = gradient.stops[index - 1];
    const next = gradient.stops[index];
    if (offset <= next.offset) {
      const localOffset = (offset - previous.offset) / (next.offset - previous.offset);
      return mixColor(previous.color, next.color, clamp(localOffset));
    }
  }

  return gradient.stops.at(-1)?.color ?? [255, 255, 255];
}

function clamp(value: number): number {
  return Math.min(1, Math.max(0, value));
}

function mixColor(from: Color, to: Color, offset: number): Color {
  return [
    Math.round(from[0] + (to[0] - from[0]) * offset),
    Math.round(from[1] + (to[1] - from[1]) * offset),
    Math.round(from[2] + (to[2] - from[2]) * offset),
  ];
}

function addColor(target: Color, color: Color): void {
  target[0] += color[0];
  target[1] += color[1];
  target[2] += color[2];
}

function renderTextLogo(pixels: Pixel[][]): string[] {
  return pairRows(pixels).map(([topRow, bottomRow]) => (
    topRow.map((top, index) => renderTextCell(top, bottomRow[index])).join('').trimEnd()
  ));
}

function renderTextCell(top: Pixel, bottom: Pixel): string {
  const hasTop = top.alpha >= FILL_THRESHOLD;
  const hasBottom = bottom.alpha >= FILL_THRESHOLD;
  if (hasTop && hasBottom) {
    return '█';
  }
  if (hasTop) {
    return '▀';
  }
  return hasBottom ? '▄' : ' ';
}

function renderAnsiLogo(pixels: Pixel[][]): string[] {
  return pairRows(pixels).map(([topRow, bottomRow]) => (
    topRow.map((top, index) => renderAnsiCell(top, bottomRow[index])).join('').trimEnd()
  ));
}

function renderAnsiCell(top: Pixel, bottom: Pixel): string {
  const hasTop = top.alpha >= FILL_THRESHOLD;
  const hasBottom = bottom.alpha >= FILL_THRESHOLD;
  if (!hasTop && !hasBottom) {
    return ' ';
  }
  if (hasTop && hasBottom) {
    return `${foreground(top.color)}${background(bottom.color)}▀${RESET}`;
  }
  return hasTop ? `${foreground(top.color)}▀\u001b[39m` : `${foreground(bottom.color)}▄\u001b[39m`;
}

function pairRows<T>(rows: T[][]): [T[], T[]][] {
  const pairs: [T[], T[]][] = [];
  for (let index = 0; index < rows.length; index += 2) {
    pairs.push([rows[index], rows[index + 1]]);
  }
  return pairs;
}

function foreground([red, green, blue]: Color): string {
  return `\u001b[38;2;${red};${green};${blue}m`;
}

function background([red, green, blue]: Color): string {
  return `\u001b[48;2;${red};${green};${blue}m`;
}

function hexToRgb(hexColor: string): Color {
  const color = hexColor.replace('#', '');
  return [
    Number.parseInt(color.slice(0, 2), 16),
    Number.parseInt(color.slice(2, 4), 16),
    Number.parseInt(color.slice(4, 6), 16),
  ];
}

function formatLines(lines: string[]): string {
  return lines.map((line) => JSON.stringify(line)).join('\n  + \'\\n\' + ');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  main();
}
